#!/usr/bin/env bash

case $OSTYPE in
    cygwin)
        echo "No root user on Cygwin"
        exit 1
        ;;
    Interix)
        echo "Administrator:+Administrators"
        ;;
    darwin*)
        echo "root:wheel"
        ;;
    solaris*)
        echo "root:bin"
        ;;
    linux-gnu)
        echo "root:root"
        ;;
    *)
        echo "root:root"
        ;;
esac
