name: Build and Release Miranda

on:
  push:
    tags:
      - "v*"  # Trigger only when a version tag (e.g., v2.066) is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential

      - name: Build project
        run: make release

      - name: Find release artifact
        id: find_artifact
        run: |
          ARTIFACT_PATH=$(ls dist/miranda-*.tgz | head -n 1)
          echo "ARTIFACT=$ARTIFACT_PATH" >> $GITHUB_ENV

      - name: Upload artifact for debugging
        uses: actions/upload-artifact@v4
        with:
          name: miranda-release
          path: ${{ env.ARTIFACT }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for changelog generation

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: miranda-release
          path: dist

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Generate changelog
        id: generate_changelog
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | grep -v $GITHUB_REF_NAME | head -n 1 || echo "")
          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found, showing all commits."
            git log --pretty=format:"- %s (%h)" > changelog.txt
          else
            echo "Generating changelog from $PREV_TAG to $GITHUB_REF_NAME"
            git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" > changelog.txt
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          cat changelog.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Miranda Release ${{ env.VERSION }}
          files: dist/miranda-*.tgz
          body: |
            ## Changes in ${{ env.VERSION }}

            ${{ env.CHANGELOG }}

            **Download:**
            - [miranda-${{ env.VERSION }}.tgz](https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/miranda-${{ env.VERSION }}.tgz)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
