name: Docker Image CI

on:
  workflow_run:
    workflows: ["Build project"]
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download miranda artifacts
        uses: actions/download-artifact@v4
        with:
          name: mira-runtime
          path: ./docker-context

      - name: Create slim Docker image
        run: |
          # Create Dockerfile
          cat <<'EOF' > docker-context/Dockerfile
          FROM debian:bookworm-slim

          # Copy all necessary files
          COPY mira.1 /usr/share/man/man1/mira.1
          COPY miralib/ /usr/local/lib/miralib/
          COPY mira /usr/local/bin/mira

          # Optional: make man page available (only if man is installed in container)
          RUN chmod +x /usr/local/bin/mira && \
              mkdir -p /usr/share/man/man1 && \
              gzip -f /usr/share/man/man1/mira.1 || true

          ENV MIRALIB=/usr/local/lib/miralib
          ENTRYPOINT ["/usr/local/bin/mira"]
          EOF

          docker build -t mrallo/mira:latest docker-context

      - name: Login and push to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          if [ -n "$DOCKERHUB_USERNAME" ]; then
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            run: docker push mrallo/mira:latest
          else
            echo "Skipping Docker push: DOCKERHUB_USERNAME not set"
          fi
 
